package optionschain.predictor.model;
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.05 at 09:49:21 PM PDT 
//




import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="option-chain-results">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="bid" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="ask" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="bid-ask-size" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="last" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="open" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="high" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="low" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="close" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="quote-punctuality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="option-date" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="expiration-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="days-to-expiration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="option-strike" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="strike-price" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="standard-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="put">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="option-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="bid" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                 &lt;element name="ask" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="bid-ask-size" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="last" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                 &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="open-interest" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="real-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="underlying-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="gamma" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="theta" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="vega" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="rho" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="implied-volatility" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="time-value-index" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="multiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="change-percent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                 &lt;element name="in-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="near-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="theoretical-value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="deliverable-list">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="cash-in-lieu-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                           &lt;element name="cash-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                           &lt;element name="index-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="row">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                     &lt;element name="shares" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "result",
    "optionChainResults"
})
@XmlRootElement(name = "amtd")
public class Amtd {

    @XmlElement(required = true)
    protected String result;
    @XmlElement(name = "option-chain-results", required = true)
    protected Amtd.OptionChainResults optionChainResults;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResult(String value) {
        this.result = value;
    }

    /**
     * Gets the value of the optionChainResults property.
     * 
     * @return
     *     possible object is
     *     {@link Amtd.OptionChainResults }
     *     
     */
    public Amtd.OptionChainResults getOptionChainResults() {
        return optionChainResults;
    }

    /**
     * Sets the value of the optionChainResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amtd.OptionChainResults }
     *     
     */
    public void setOptionChainResults(Amtd.OptionChainResults value) {
        this.optionChainResults = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="bid" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="ask" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="bid-ask-size" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="last" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="open" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="high" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="low" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="close" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="quote-punctuality" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="option-date" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="expiration-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="days-to-expiration" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="option-strike" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="strike-price" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="standard-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="put">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="option-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="bid" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                       &lt;element name="ask" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                                       &lt;element name="bid-ask-size" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                                       &lt;element name="last" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                       &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="open-interest" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="real-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="underlying-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="gamma" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="theta" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="vega" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="rho" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="implied-volatility" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="time-value-index" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="multiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="change-percent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                       &lt;element name="in-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="near-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="theoretical-value" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                       &lt;element name="deliverable-list">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="cash-in-lieu-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                                 &lt;element name="cash-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                                 &lt;element name="index-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="row">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                           &lt;element name="shares" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "error",
        "symbol",
        "description",
        "bid",
        "ask",
        "bidAskSize",
        "last",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "change",
        "quotePunctuality",
        "time",
        "optionDate"
    })
    public static class OptionChainResults {

        @XmlElement(required = true)
        protected Object error;
        @XmlElement(required = true)
        protected String symbol;
        @XmlElement(required = true)
        protected String description;
        protected double bid;
        protected double ask;
        @XmlElement(name = "bid-ask-size", required = true)
        protected String bidAskSize;
        protected double last;
        protected double open;
        protected int high;
        protected double low;
        protected double close;
        protected double volume;
        protected int change;
        @XmlElement(name = "quote-punctuality", required = true)
        protected String quotePunctuality;
        @XmlElement(required = true)
        protected String time;
        @XmlElement(name = "option-date", required = true)
        protected List<Amtd.OptionChainResults.OptionDate> optionDate;

        /**
         * Gets the value of the error property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getError() {
            return error;
        }

        /**
         * Sets the value of the error property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setError(Object value) {
            this.error = value;
        }

        /**
         * Gets the value of the symbol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSymbol() {
            return symbol;
        }

        /**
         * Sets the value of the symbol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSymbol(String value) {
            this.symbol = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the bid property.
         * 
         */
        public double getBid() {
            return bid;
        }

        /**
         * Sets the value of the bid property.
         * 
         */
        public void setBid(double value) {
            this.bid = value;
        }

        /**
         * Gets the value of the ask property.
         * 
         */
        public double getAsk() {
            return ask;
        }

        /**
         * Sets the value of the ask property.
         * 
         */
        public void setAsk(double value) {
            this.ask = value;
        }

        /**
         * Gets the value of the bidAskSize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBidAskSize() {
            return bidAskSize;
        }

        /**
         * Sets the value of the bidAskSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBidAskSize(String value) {
            this.bidAskSize = value;
        }

        /**
         * Gets the value of the last property.
         * 
         */
        public double getLast() {
            return last;
        }

        /**
         * Sets the value of the last property.
         * 
         */
        public void setLast(double value) {
            this.last = value;
        }

        /**
         * Gets the value of the open property.
         * 
         */
        public double getOpen() {
            return open;
        }

        /**
         * Sets the value of the open property.
         * 
         */
        public void setOpen(double value) {
            this.open = value;
        }

        /**
         * Gets the value of the high property.
         * 
         */
        public int getHigh() {
            return high;
        }

        /**
         * Sets the value of the high property.
         * 
         */
        public void setHigh(int value) {
            this.high = value;
        }

        /**
         * Gets the value of the low property.
         * 
         */
        public double getLow() {
            return low;
        }

        /**
         * Sets the value of the low property.
         * 
         */
        public void setLow(double value) {
            this.low = value;
        }

        /**
         * Gets the value of the close property.
         * 
         */
        public double getClose() {
            return close;
        }

        /**
         * Sets the value of the close property.
         * 
         */
        public void setClose(double value) {
            this.close = value;
        }

        /**
         * Gets the value of the volume property.
         * 
         */
        public double getVolume() {
            return volume;
        }

        /**
         * Sets the value of the volume property.
         * 
         */
        public void setVolume(double value) {
            this.volume = value;
        }

        /**
         * Gets the value of the change property.
         * 
         */
        public int getChange() {
            return change;
        }

        /**
         * Sets the value of the change property.
         * 
         */
        public void setChange(int value) {
            this.change = value;
        }

        /**
         * Gets the value of the quotePunctuality property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQuotePunctuality() {
            return quotePunctuality;
        }

        /**
         * Sets the value of the quotePunctuality property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQuotePunctuality(String value) {
            this.quotePunctuality = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(String value) {
            this.time = value;
        }

        /**
         * Gets the value of the optionDate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the optionDate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOptionDate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Amtd.OptionChainResults.OptionDate }
         * 
         * 
         */
        public List<Amtd.OptionChainResults.OptionDate> getOptionDate() {
            if (optionDate == null) {
                optionDate = new ArrayList<Amtd.OptionChainResults.OptionDate>();
            }
            return this.optionDate;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="expiration-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="days-to-expiration" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="option-strike" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="strike-price" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="standard-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="put">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="option-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="bid" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                             &lt;element name="ask" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                             &lt;element name="bid-ask-size" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                             &lt;element name="last" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                             &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="open-interest" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="real-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="underlying-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="gamma" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="theta" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="vega" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="rho" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="implied-volatility" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="time-value-index" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="multiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="change-percent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                             &lt;element name="in-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="near-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="theoretical-value" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                             &lt;element name="deliverable-list">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="cash-in-lieu-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                                       &lt;element name="cash-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                                       &lt;element name="index-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="row">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                 &lt;element name="shares" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "date",
            "expirationType",
            "daysToExpiration",
            "optionStrike"
        })
        public static class OptionDate {

            protected int date;
            @XmlElement(name = "expiration-type", required = true)
            protected String expirationType;
            @XmlElement(name = "days-to-expiration")
            protected int daysToExpiration;
            @XmlElement(name = "option-strike", required = true)
            protected List<Amtd.OptionChainResults.OptionDate.OptionStrike> optionStrike;

            /**
             * Gets the value of the date property.
             * 
             */
            public int getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             */
            public void setDate(int value) {
                this.date = value;
            }

            /**
             * Gets the value of the expirationType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpirationType() {
                return expirationType;
            }

            /**
             * Sets the value of the expirationType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpirationType(String value) {
                this.expirationType = value;
            }

            /**
             * Gets the value of the daysToExpiration property.
             * 
             */
            public int getDaysToExpiration() {
                return daysToExpiration;
            }

            /**
             * Sets the value of the daysToExpiration property.
             * 
             */
            public void setDaysToExpiration(int value) {
                this.daysToExpiration = value;
            }

            /**
             * Gets the value of the optionStrike property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the optionStrike property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOptionStrike().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Amtd.OptionChainResults.OptionDate.OptionStrike }
             * 
             * 
             */
            public List<Amtd.OptionChainResults.OptionDate.OptionStrike> getOptionStrike() {
                if (optionStrike == null) {
                    optionStrike = new ArrayList<Amtd.OptionChainResults.OptionDate.OptionStrike>();
                }
                return this.optionStrike;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="strike-price" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="standard-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="put">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="option-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="bid" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                   &lt;element name="ask" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *                   &lt;element name="bid-ask-size" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *                   &lt;element name="last" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                   &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="open-interest" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="real-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="underlying-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="gamma" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="theta" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="vega" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="rho" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="implied-volatility" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="time-value-index" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="multiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="change-percent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                   &lt;element name="in-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="near-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="theoretical-value" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                   &lt;element name="deliverable-list">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="cash-in-lieu-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                             &lt;element name="cash-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                             &lt;element name="index-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="row">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                       &lt;element name="shares" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "strikePrice",
                "standardOption",
                "put"
            })
            public static class OptionStrike {

                @XmlElement(name = "strike-price")
                protected int strikePrice;
                @XmlElement(name = "standard-option", required = true)
                protected String standardOption;
                @XmlElement(required = true)
                protected Amtd.OptionChainResults.OptionDate.OptionStrike.Put put;

                /**
                 * Gets the value of the strikePrice property.
                 * 
                 */
                public int getStrikePrice() {
                    return strikePrice;
                }

                /**
                 * Sets the value of the strikePrice property.
                 * 
                 */
                public void setStrikePrice(int value) {
                    this.strikePrice = value;
                }

                /**
                 * Gets the value of the standardOption property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStandardOption() {
                    return standardOption;
                }

                /**
                 * Sets the value of the standardOption property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStandardOption(String value) {
                    this.standardOption = value;
                }

                /**
                 * Gets the value of the put property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Amtd.OptionChainResults.OptionDate.OptionStrike.Put }
                 *     
                 */
                public Amtd.OptionChainResults.OptionDate.OptionStrike.Put getPut() {
                    return put;
                }

                /**
                 * Sets the value of the put property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Amtd.OptionChainResults.OptionDate.OptionStrike.Put }
                 *     
                 */
                public void setPut(Amtd.OptionChainResults.OptionDate.OptionStrike.Put value) {
                    this.put = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="option-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="bid" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *         &lt;element name="ask" type="{http://www.w3.org/2001/XMLSchema}double"/>
                 *         &lt;element name="bid-ask-size" type="{http://www.w3.org/2001/XMLSchema}double"/>
                 *         &lt;element name="last" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="open-interest" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="real-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="underlying-symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="gamma" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="theta" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="vega" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="rho" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="implied-volatility" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="time-value-index" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="multiplier" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="change-percent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *         &lt;element name="in-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="near-the-money" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="theoretical-value" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *         &lt;element name="deliverable-list">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="cash-in-lieu-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *                   &lt;element name="cash-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *                   &lt;element name="index-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="row">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                             &lt;element name="shares" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "optionSymbol",
                    "bid",
                    "ask",
                    "bidAskSize",
                    "last",
                    "volume",
                    "openInterest",
                    "realTime",
                    "underlyingSymbol",
                    "delta",
                    "gamma",
                    "theta",
                    "vega",
                    "rho",
                    "impliedVolatility",
                    "timeValueIndex",
                    "multiplier",
                    "change",
                    "changePercent",
                    "inTheMoney",
                    "nearTheMoney",
                    "theoreticalValue",
                    "deliverableList"
                })
                public static class Put {

                    @XmlElement(name = "option-symbol", required = true)
                    protected String optionSymbol;
                    @XmlElement(required = true)
                    protected double bid;
                    protected double ask;
                    @XmlElement(name = "bid-ask-size")
                    protected double bidAskSize;
                    @XmlElement(required = true)
                    protected double last;
                    protected int volume;
                    @XmlElement(name = "open-interest")
                    protected int openInterest;
                    @XmlElement(name = "real-time", required = true)
                    protected String realTime;
                    @XmlElement(name = "underlying-symbol", required = true)
                    protected String underlyingSymbol;
                    protected int delta;
                    protected int gamma;
                    protected int theta;
                    protected int vega;
                    protected int rho;
                    @XmlElement(name = "implied-volatility")
                    protected int impliedVolatility;
                    @XmlElement(name = "time-value-index")
                    protected int timeValueIndex;
                    protected int multiplier;
                    protected int change;
                    @XmlElement(name = "change-percent", required = true)
                    protected double changePercent;
                    @XmlElement(name = "in-the-money", required = true)
                    protected String inTheMoney;
                    @XmlElement(name = "near-the-money", required = true)
                    protected String nearTheMoney;
                    @XmlElement(name = "theoretical-value")
                    protected int theoreticalValue;
                    @XmlElement(name = "deliverable-list", required = true)
                    protected Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList deliverableList;

                    /**
                     * Gets the value of the optionSymbol property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getOptionSymbol() {
                        return optionSymbol;
                    }

                    /**
                     * Sets the value of the optionSymbol property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setOptionSymbol(String value) {
                        this.optionSymbol = value;
                    }

                    /**
                     * Gets the value of the bid property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Object }
                     *     
                     */
                    public double getBid() {
                        return bid;
                    }

                    /**
                     * Sets the value of the bid property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Object }
                     *     
                     */
                    public void setBid(double value) {
                        this.bid = value;
                    }

                    /**
                     * Gets the value of the ask property.
                     * 
                     */
                    public double getAsk() {
                        return ask;
                    }

                    /**
                     * Sets the value of the ask property.
                     * 
                     */
                    public void setAsk(double value) {
                        this.ask = value;
                    }

                    /**
                     * Gets the value of the bidAskSize property.
                     * 
                     */
                    public double getBidAskSize() {
                        return bidAskSize;
                    }

                    /**
                     * Sets the value of the bidAskSize property.
                     * 
                     */
                    public void setBidAskSize(double value) {
                        this.bidAskSize = value;
                    }

                    /**
                     * Gets the value of the last property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Object }
                     *     
                     */
                    public double getLast() {
                        return last;
                    }

                    /**
                     * Sets the value of the last property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Object }
                     *     
                     */
                    public void setLast(double value) {
                        this.last = value;
                    }

                    /**
                     * Gets the value of the volume property.
                     * 
                     */
                    public int getVolume() {
                        return volume;
                    }

                    /**
                     * Sets the value of the volume property.
                     * 
                     */
                    public void setVolume(int value) {
                        this.volume = value;
                    }

                    /**
                     * Gets the value of the openInterest property.
                     * 
                     */
                    public int getOpenInterest() {
                        return openInterest;
                    }

                    /**
                     * Sets the value of the openInterest property.
                     * 
                     */
                    public void setOpenInterest(int value) {
                        this.openInterest = value;
                    }

                    /**
                     * Gets the value of the realTime property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRealTime() {
                        return realTime;
                    }

                    /**
                     * Sets the value of the realTime property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRealTime(String value) {
                        this.realTime = value;
                    }

                    /**
                     * Gets the value of the underlyingSymbol property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUnderlyingSymbol() {
                        return underlyingSymbol;
                    }

                    /**
                     * Sets the value of the underlyingSymbol property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUnderlyingSymbol(String value) {
                        this.underlyingSymbol = value;
                    }

                    /**
                     * Gets the value of the delta property.
                     * 
                     */
                    public int getDelta() {
                        return delta;
                    }

                    /**
                     * Sets the value of the delta property.
                     * 
                     */
                    public void setDelta(int value) {
                        this.delta = value;
                    }

                    /**
                     * Gets the value of the gamma property.
                     * 
                     */
                    public int getGamma() {
                        return gamma;
                    }

                    /**
                     * Sets the value of the gamma property.
                     * 
                     */
                    public void setGamma(int value) {
                        this.gamma = value;
                    }

                    /**
                     * Gets the value of the theta property.
                     * 
                     */
                    public int getTheta() {
                        return theta;
                    }

                    /**
                     * Sets the value of the theta property.
                     * 
                     */
                    public void setTheta(int value) {
                        this.theta = value;
                    }

                    /**
                     * Gets the value of the vega property.
                     * 
                     */
                    public int getVega() {
                        return vega;
                    }

                    /**
                     * Sets the value of the vega property.
                     * 
                     */
                    public void setVega(int value) {
                        this.vega = value;
                    }

                    /**
                     * Gets the value of the rho property.
                     * 
                     */
                    public int getRho() {
                        return rho;
                    }

                    /**
                     * Sets the value of the rho property.
                     * 
                     */
                    public void setRho(int value) {
                        this.rho = value;
                    }

                    /**
                     * Gets the value of the impliedVolatility property.
                     * 
                     */
                    public int getImpliedVolatility() {
                        return impliedVolatility;
                    }

                    /**
                     * Sets the value of the impliedVolatility property.
                     * 
                     */
                    public void setImpliedVolatility(int value) {
                        this.impliedVolatility = value;
                    }

                    /**
                     * Gets the value of the timeValueIndex property.
                     * 
                     */
                    public int getTimeValueIndex() {
                        return timeValueIndex;
                    }

                    /**
                     * Sets the value of the timeValueIndex property.
                     * 
                     */
                    public void setTimeValueIndex(int value) {
                        this.timeValueIndex = value;
                    }

                    /**
                     * Gets the value of the multiplier property.
                     * 
                     */
                    public int getMultiplier() {
                        return multiplier;
                    }

                    /**
                     * Sets the value of the multiplier property.
                     * 
                     */
                    public void setMultiplier(int value) {
                        this.multiplier = value;
                    }

                    /**
                     * Gets the value of the change property.
                     * 
                     */
                    public int getChange() {
                        return change;
                    }

                    /**
                     * Sets the value of the change property.
                     * 
                     */
                    public void setChange(int value) {
                        this.change = value;
                    }

                    /**
                     * Gets the value of the changePercent property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Object }
                     *     
                     */
                    public double getChangePercent() {
                        return changePercent;
                    }

                    /**
                     * Sets the value of the changePercent property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Object }
                     *     
                     */
                    public void setChangePercent(double value) {
                        this.changePercent = value;
                    }

                    /**
                     * Gets the value of the inTheMoney property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getInTheMoney() {
                        return inTheMoney;
                    }

                    /**
                     * Sets the value of the inTheMoney property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setInTheMoney(String value) {
                        this.inTheMoney = value;
                    }

                    /**
                     * Gets the value of the nearTheMoney property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNearTheMoney() {
                        return nearTheMoney;
                    }

                    /**
                     * Sets the value of the nearTheMoney property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNearTheMoney(String value) {
                        this.nearTheMoney = value;
                    }

                    /**
                     * Gets the value of the theoreticalValue property.
                     * 
                     */
                    public int getTheoreticalValue() {
                        return theoreticalValue;
                    }

                    /**
                     * Sets the value of the theoreticalValue property.
                     * 
                     */
                    public void setTheoreticalValue(int value) {
                        this.theoreticalValue = value;
                    }

                    /**
                     * Gets the value of the deliverableList property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList }
                     *     
                     */
                    public Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList getDeliverableList() {
                        return deliverableList;
                    }

                    /**
                     * Sets the value of the deliverableList property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList }
                     *     
                     */
                    public void setDeliverableList(Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList value) {
                        this.deliverableList = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="cash-in-lieu-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                     *         &lt;element name="cash-dollar-amount" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                     *         &lt;element name="index-option" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="row">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                   &lt;element name="shares" type="{http://www.w3.org/2001/XMLSchema}int"/>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "cashInLieuDollarAmount",
                        "cashDollarAmount",
                        "indexOption",
                        "row"
                    })
                    public static class DeliverableList {

                        @XmlElement(name = "cash-in-lieu-dollar-amount", required = true)
                        protected Object cashInLieuDollarAmount;
                        @XmlElement(name = "cash-dollar-amount", required = true)
                        protected Object cashDollarAmount;
                        @XmlElement(name = "index-option", required = true)
                        protected String indexOption;
                        @XmlElement(required = true)
                        protected Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList.Row row;

                        /**
                         * Gets the value of the cashInLieuDollarAmount property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Object }
                         *     
                         */
                        public Object getCashInLieuDollarAmount() {
                            return cashInLieuDollarAmount;
                        }

                        /**
                         * Sets the value of the cashInLieuDollarAmount property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Object }
                         *     
                         */
                        public void setCashInLieuDollarAmount(Object value) {
                            this.cashInLieuDollarAmount = value;
                        }

                        /**
                         * Gets the value of the cashDollarAmount property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Object }
                         *     
                         */
                        public Object getCashDollarAmount() {
                            return cashDollarAmount;
                        }

                        /**
                         * Sets the value of the cashDollarAmount property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Object }
                         *     
                         */
                        public void setCashDollarAmount(Object value) {
                            this.cashDollarAmount = value;
                        }

                        /**
                         * Gets the value of the indexOption property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getIndexOption() {
                            return indexOption;
                        }

                        /**
                         * Sets the value of the indexOption property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setIndexOption(String value) {
                            this.indexOption = value;
                        }

                        /**
                         * Gets the value of the row property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList.Row }
                         *     
                         */
                        public Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList.Row getRow() {
                            return row;
                        }

                        /**
                         * Sets the value of the row property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList.Row }
                         *     
                         */
                        public void setRow(Amtd.OptionChainResults.OptionDate.OptionStrike.Put.DeliverableList.Row value) {
                            this.row = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *         &lt;element name="shares" type="{http://www.w3.org/2001/XMLSchema}int"/>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "symbol",
                            "shares"
                        })
                        public static class Row {

                            @XmlElement(required = true)
                            protected String symbol;
                            protected int shares;

                            /**
                             * Gets the value of the symbol property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getSymbol() {
                                return symbol;
                            }

                            /**
                             * Sets the value of the symbol property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setSymbol(String value) {
                                this.symbol = value;
                            }

                            /**
                             * Gets the value of the shares property.
                             * 
                             */
                            public int getShares() {
                                return shares;
                            }

                            /**
                             * Sets the value of the shares property.
                             * 
                             */
                            public void setShares(int value) {
                                this.shares = value;
                            }

							@Override
							public String toString() {
								return "Row [symbol=" + symbol + ", shares=" + shares + "]";
							}

                        }


						@Override
						public String toString() {
							return "DeliverableList [cashInLieuDollarAmount=" + cashInLieuDollarAmount
									+ ", cashDollarAmount=" + cashDollarAmount + ", indexOption=" + indexOption
									+ ", row=" + row + "]";
						}

                    }


					@Override
					public String toString() {
						return "Put [optionSymbol=" + optionSymbol + ", bid=" + bid + ", ask=" + ask + ", bidAskSize="
								+ bidAskSize + ", last=" + last + ", volume=" + volume + ", openInterest="
								+ openInterest + ", realTime=" + realTime + ", underlyingSymbol=" + underlyingSymbol
								+ ", delta=" + delta + ", gamma=" + gamma + ", theta=" + theta + ", vega=" + vega
								+ ", rho=" + rho + ", impliedVolatility=" + impliedVolatility + ", timeValueIndex="
								+ timeValueIndex + ", multiplier=" + multiplier + ", change=" + change
								+ ", changePercent=" + changePercent + ", inTheMoney=" + inTheMoney + ", nearTheMoney="
								+ nearTheMoney + ", theoreticalValue=" + theoreticalValue + ", deliverableList="
								+ deliverableList + "]";
					}

                }


				@Override
				public String toString() {
					return "OptionStrike [strikePrice=" + strikePrice + ", standardOption=" + standardOption + ", put="
							+ put + "]";
				}

            }


			@Override
			public String toString() {
				return "OptionDate [date=" + date + ", expirationType=" + expirationType + ", daysToExpiration="
						+ daysToExpiration + ", optionStrike=" + optionStrike + "]";
			}

        }


		@Override
		public String toString() {
			return "OptionChainResults [error=" + error + ", symbol=" + symbol + ", description=" + description
					+ ", bid=" + bid + ", ask=" + ask + ", bidAskSize=" + bidAskSize + ", last=" + last + ", open="
					+ open + ", high=" + high + ", low=" + low + ", close=" + close + ", volume=" + volume + ", change="
					+ change + ", quotePunctuality=" + quotePunctuality + ", time=" + time + ", optionDate="
					+ optionDate + "]";
		}

    }


	@Override
	public String toString() {
		return "Amtd [result=" + result + ", optionChainResults=" + optionChainResults + "]";
	}

}
